robot:
  robot_specifications:
    - footprint:
        footprint_specifications:
          radius: 0.2
          points:
            []
    - initial_pose:
        x: 0
        y: 0
        theta: 0
    - laser:
        laser_specifications:
          max_angle: 3.141593
          min_angle: -3.141593
          max_range: 8
          min_range: 0
          num_rays: 360
          frequency: 10
          frame_id: laser_0
          pose:
            x: 0
            y: 0
            theta: 0
          noise:
            noise_specifications:
              noise_mean: 0
              noise_std: 0
