robot_radius: 0.2

update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 4.0
raytrace_range: 4.0

#layer definitions


obstacle_layer:
    max_obstacle_height: 2.0
    observation_sources: laser
    laser: {sensor_frame: robot0_laser_0, data_type: LaserScan, topic: /robot0/laser_0, clearing: true, marking: true, min_obstacle_height: 0.0, max_obstacle_height: 2.0}

inflation_layer:
    inflation_radius: 0.2
