rsm_msgs/OperationMode operationMode	#Info about operation mode including emergency stop
---
bool success                       				# Indicate successful run of triggered service
string message                      			# Informational, e.g. for error messages