footprint: [[-0.38, -0.24], [-0.38, 0.24], [0.38, 0.24], [0.38, -0.24]]
footprint_padding: 0.01

robot_base_frame: base_footprint
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 2.0

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions


obstacle_layer:
    observation_sources: laser
    laser: {sensor_frame: laser, data_type: LaserScan, topic: scan, clearing: true, marking: true}

inflation_layer:
    inflation_radius: 1.0
