obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
#robot_radius: 0.105

obstacle_layer:
    observation_sources: laser #camera
    laser: {sensor_frame: base_laser, data_type: LaserScan, topic: scan, clearing: true, marking: true}
#   laser: {sensor_frame: lms_front_scan_frame, data_type: LaserScan, topic: lms_front/scan, clearing: true, marking: true}
#    camera: {sensor_frame: camera_link, data_type: PointCloud2, topic: camera/depth/points, clearing: true, min_obstacle_height: 0.25}

inflation_layer:
    inflation_radius: 1.0
    cost_scaling_factor: 2.0