local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  rolling_window: true
  width: 6.0
  height: 6.0
  
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
