local_costmap:
  global_frame: map
  rolling_window: true
  width: 6.0
  height: 6.0

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: static_layer, type: 'costmap_2d::StaticLayer'}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}